# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: aca-windup
resourceGroup: rg-aca-windup
infra:
    provider: "bicep"
    path: "infra"
    module: main
    host: containerapp
services:
  ui:
    project: ./src
    module: app/ui.bicep
    language: java
    host: containerapp
  cli:
    project: ./src
    module: app/cli.bicep
    language: java
    host: containerapp    
pipeline:
    provider: "github"
